### ISSUE TITLE
show a .re example in readme

### ISSUE THREAD

**Issue by jthegedus** [utkarshkukreti/bs-preact#1]
Users who prefer `reason` over `ocaml` syntax and who are unfamiliar with the usage of annotations like `let [@hook]` may have a hard time understanding where the annotations go in a Reason formatted codebase.

Putting this example:

```ocaml
let useDoubleReducer =
 fun [@preact.hook] (reducer, initialValue) ->
  let[@hook] state, dispatch = P.useReducer reducer initialValue in
  let dispatchTwice action =
    let () = dispatch action in
    dispatch action
  in
  state, dispatchTwice

let make =
 fun [@preact.component "HelloHooks"] () ->
  let reducer state action = state + action in
  let[@hook] state, dispatch = useDoubleReducer (reducer, 0) in
  P.button [ P.onClick (fun _ -> dispatch 2) ] [ P.int state ]
```

[into the ReasonML playground](https://reasonml.github.io/en/try?rrjsx=true&ocaml=DYUwLgBArgziAiB7KAjUAlEATKBjEAThALwBQEAZlAHYQDaAAgA4EgCGuYAdABaKIBrALoQAFKxz4CAGggBLanLBy2wAGqqoIAJQQAtAD5yEUGEZ9BImGDZgQsrHJhNbuHiQgAFLrBCZJhBASeIEKSirqmiDy1MamEI7OrjwAKgDucvgQHMqItGQQhSbgYrrECU4uYG7ZnHJ5McaFiVU1OfWxhQrG1rb2FUnVqRn4pKTxALZsAtEFVLSMLOycXLiIE0x5INSQAEQAEiDAwIj7-AIwuyKiuoZxJcFSEL12tbn5zzavANRvHY2FUzmc5WL79FrJDy+JCoDDYEJEcTwqSyAAMum6hW8KCgYDADToXi4eQAwsBMgIxPMIAB9fQGAatdwAJl0IkJ3gUkBe0SEQA
) outputs this: 

```reason
let useDoubleReducer =
  [@preact.hook]
  (
    ((reducer, initialValue)) =>
      [@hook]
      {
        let (state, dispatch) = P.useReducer(reducer, initialValue);
        let dispatchTwice = action => {
          let () = dispatch(action);
          dispatch(action);
        };

        (state, dispatchTwice);
      }
  );

let make =
  [@preact.component "HelloHooks"]
  (
    () => {
      let reducer = (state, action) => state + action;
      [@hook]
      {
        let (state, dispatch) = useDoubleReducer((reducer, 0));
        P.button([P.onClick(_ => dispatch(2))], [P.int(state)]);
      };
    }
  );
```

As someone who does not know where annotations are supposed to go in Reason formatted code it is unclear if this translation is in fact correct.

PS: thanks for your work, really like the hooks validation at compile time :ok_hand: 

**Proposed solution**

* show a reasonml example
* like to resources/docs on annotation usage in reasonml

**Comment by utkarshkukreti** [comment]
Thanks for the kind words!

I've ported HelloWorld and HelloCustomHooks examples to ReasonML and added them to the README.

I've referenced this issue in all the commits that address this issue so they should appear above this comment.

Please let me know if you still have any questions, comments, or suggestions!

**Comment by jthegedus** [comment]
Thanks for the quick response, I appreciate the changes :100:
